### ISSUE TITLE
config.js file changes are not reflected in the gui

### ISSUE THREAD

**Issue by delebash** [vladmandic/human#19]
Tested demo folder index.html using only hand pose enabled

1) Open config.js
2) Change hand>maxHands: to 1
3) Launch index.html and the gui still has Max Objects set to 10
I also tested another variable by setting backend to wasm but the change was also not updated in the gui

**Comment by vladmandic** [comment]
demo has default configuration overrides set in `demo/browser.js:config` - simply for purpose of having a local variable so menu can bind something to directly  

if those are removed, then defaults from `config.js` are used

**Comment by delebash** [comment]
Great thanks for the explanation

**Comment by delebash** [comment]
Did not mean to close since this is outstanding :)

**Comment by vladmandic** [comment]
i've updated the docs, will be up in the next publish, it's ok to close now.

**Comment by delebash** [comment]
I still do not see any changes in the gui after changing config.js.  Per your comment I do not see a config object in browser.js.  I do see variables in the setupMenu function as   menu.addBool('Face Detect', human.config.face, 'enabled');.  My expectation would be that the gui would reflect the changes made in config.js so if I have in my config  
 face: {
    enabled: false
}

Than the gui slider FACE DETECT would load as disabled.  Am I doing something wrong?

**Comment by delebash** [comment]
Off Topic:

When I push commit's to my fork do you get notified on github.  The reason I am asking is that I don't want to bother you when I am making changes to my fork.

**Comment by vladmandic** [comment]
i removed config object from `browser.js` earlier today, demo should now link directly to config from main library, meaning `config.js`.

and no, i don't get notifications for separate forks.

**Comment by delebash** [comment]
npm run rebuild is not a valid script.  Did you mean npm rebuild?  Also is there a way to use the config without running npm rebuild?  I am using the demo/browser.js not the dist/demo-browser-index.js

**Comment by vladmandic** [comment]
it's `npm run build` (sorry, my typo)
and no, config.js is included in human.js (esm/node/whatever) library, so library needs to be rebuild before it's even exposed to client.

**Comment by vladmandic** [comment]
you *could* import config.js into your app directly and then use human with your version passing it as override.
something like
```js
const myConfig = require('config.js).default;
human.detect(image, myconfig);
```
(or equivalent import statement if you're using esm and not node)

**Comment by delebash** [comment]
Thanks it works as expected.  Suggestion would it not be better to just have a config.json file that can be loaded at runtime?   I am testing the demo and in my case I only want the hand enabled when I open the page and everything else disabled.  I also may want to start it with hand and face enabled but then I have to rebuild.  I am running this in an IDE that has its own web server and importing browser.js so I don't actually need to build anything unless I change human.js I can just refresh the page.

By the way human is awesome thank you very very much for the hard work!!!

**Comment by delebash** [comment]
Ok importing config.js works fine for me.  Thanks.

**Comment by vladmandic** [comment]
that's the whole points of having second param to human.load() or human.detect() - to pass user configuration.
then it's merged with defaults that come from config.js.

user configuration can be single flag or entire config or anything in-between. and no harm if user config is entire config.js as it's just going to be merged into single object anyhow.

and yes, it can be a json or js as well.

**Comment by delebash** [comment]
I understand about the defaults and overriding.  I have tried the override and it does not seem to be working

browser.js

import myConfig from './config.js'

function main ....
     console.log(myConfig.backend) // = webgl
      await human.detect(warmup, myConfig);

No change in gui sliders

**Comment by vladmandic** [comment]
in demo, setupMenu() is called before human.load() or human.detect(), so it menu binds to default values - your values have not yet been merged at that time.
if you want to directly bind menu to your values regardless, change setupMenu parameters to use your object instead of `human.config`.

**Comment by delebash** [comment]
Works perfectly.
