### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by ost12666** [vladmandic/human#55]
https://github.com/vladmandic/human/wiki/Outputs says emotions are in the result root but it is actually inside the face object.

Also I am not sure human.defaults work, at least sometimes it returned undefined

**Comment by ost12666** [comment]
also there is a type 'discust' should be 'disgust'

**Comment by ost12666** [comment]
and 'surpise' should be 'surprise'

not sure if those are doc errors or also errors in the code

**Comment by ost12666** [comment]
I guess code const annotations = ['angry', 'disgust', 'fear', 'happy', 'sad', 'surpise', 'neutral'];

**Comment by vladmandic** [comment]
you're correct. and the code was ok (in `emotion/emotion.js`, but docs were not).
fixed via <https://github.com/vladmandic/human/wiki/Outputs/ad583a5aa931611f981f1d2287e98343df5393d8>

**Comment by ost12666** [comment]
Code is still wrong in surprise:

const annotations = ['angry', 'disgust', 'fear', 'happy', 'sad', 'surpise', 'neutral'];

While doc is corrected:

// <string> 'angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral'

**Comment by vladmandic** [comment]
it was missing a git push - sorry :)

**Comment by ost12666** [comment]
The library is awesome! thanks

I really like the gestures, very useful

**Comment by vladmandic** [comment]
Thanks!

Feel free to suggest additional gestures, current ones are just few samples.

**Comment by ost12666** [comment]
I am now trying to implement head nods detection using head down and head up gestures so its more time based than static gestures. I implemented raise hand by looking at all gestures that has finder, hand or finger name in it. I am also using facing camera and face neutral for detecting user is looking at the camera.
